language: node_js
node_js:
- '6'
dist: trusty
script:
- npm run build
deploy:
  provider: npm
  email: p.dupavillon@gmail.com
  api_key:
    secure: KoZv1mZuttRVvPMlFM97l/VmMqPkV/JRzSHFMb9sllKv6c2l+ws26VM/IWHYwRrYLyLrT7Zz93x1yL25Z98xa5sEhHLcpbz/0SUjOaRnd4o9dK8Lg+mGU0TZCxIfxByR2ldNPZOf72WxZamRsEJHXJCqifTYZChdmI9K10i6SPVA8qjDGr9sHOitEUOJ0+rkrn+jgSw0qikYpeXCA8H+oHgmIyNdCOvHvwvXzv4C/t+K6so5lCCiEHguo1f3g2z2DQ40jKpJxuaQoplUlK/34kbdCnOAsiSpB0uoVjgLBoco5iozEUxrIH0uhwkknYOCfXMpqGygguT8nIdnVvHpOpGBIBIja3ky1zv31P9rbEDFBqMiflfGW3NdQBubhZJwFe3P9Gel/wqK6/Jy5BRI2NVLOQJxNQCrKNqYuaL4RrtCu09q7pYabOXDjBe4cxGRl85jmtknwFdtk8/TQj+jPkZKqlZ3zt5gpQZ08prDPRC2Kq3JEPVEuyNiWRLNYQo3MAL1ikhaBRXGPbTUZhsmnDrM3NC0DVOOlXQpeU8NpT2uLZXCWhf/zqARkskQ/bMI41+7SECnAnIxiTeOWi9KAPAZK6vXjpZPds1SaQN5hILaIpkMv67FYfWwmbBN+L2vM7B7Dh0wgi1UVmdqSL50RH5VM2D8+OWUxYzFzRAeD+M=
